### PR TITLE
Update p2p seeds in env file

### PR DESCRIPTION
**Pull request by michaeldjeffrey**
followup for #243

### CODE REVIEW

**Comment by macpie** [comment]
Is this confirmed with blockchain team?

**Comment by michaeldjeffrey** [comment]
These nodes have been confirmed by the Blockchain team.

**Comment by macpie** [comment]
Could you also update the default sys.config?

**Comment by michaeldjeffrey** [comment]
The default sys.config was updated in https://github.com/helium/router/pull/243/

**Review by macpie — APPROVED** [review]

**Pull request merged**
